### ISSUE TITLE
Launch tracking

### ISSUE THREAD

**Issue by kytrinyx** [exercism/j#1]
Edit this issue to keep track of the tasks you're working on towards launch.

We have a rough guide for how to launch a track, which is sorely outdated but
quite possibly better than nothing (I'm so sorry, I'm waaaay behind on getting
documentation updated).
https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md

Check out https://github.com/orgs/exercism/teams/track-maintainers/discussions/1
for details about the #maintainers channel in the exercism-team Slack workspace.

Please ask if you have any questions or if anything is confusing!

The next steps are roughly:

- [x] Select programming language variant (if applicable)
- [x] Select testing framework
- [x] Write first exercise
- [x] Plan initial core + optional exercises
- [ ] Add the track to the site as inactive
- [ ] Request a track icon
- [x] Write "getting started" instructions for people using the track
- [ ] Launch!
- [ ] Prepare for open source contributions from strangers

**Comment by jitwit** [comment]
Thanks! I at least have some understanding of where things should generally head from maintaining the scheme track. 

It's not completely clear how to proceed with respect to what's still relevant for version 3, but I'll just start off by adding various useful things!
