### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/j#39]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [x] [Configure online editor](https://github.com/exercism/j/issues/30)
- [x] [Add key features](https://github.com/exercism/j/issues/31)
- [x] [Add tags](https://github.com/exercism/j/issues/32)
- [x] [Add prerequisites to Practice Exercises](https://github.com/exercism/j/issues/33)
- [x] [Update status of track](https://github.com/exercism/j/issues/37)
- [x] [Update status of Concept Exercises](https://github.com/exercism/j/issues/38)
- [x] [Pass linting checks](https://github.com/exercism/j/issues/34)
- [x] [Build Test Runner](https://github.com/exercism/j/issues/35)
- [ ] [Build Analyzer and Representer](https://github.com/exercism/j/issues/36) (optional)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7
